POST http://localhost:8080/messages/1
Content-Type: application/json

{
  "dialogId" : "1",
  "text" : "Bye!"
}

###

GET http://localhost:8080/messages/1
Content-Type: application/json

###

GET http://localhost:8080/api/animals
Content-Type: application/json

###
GET http://localhost:8080/api/info/2
Content-Type: application/json